# Generated by Django 4.1.3 on 2022-11-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
